apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: subscriber-git
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: main
      url: http://github.com/0pens0/drax-tbs-demo
      sub-path: /HG.Test.PoC/MessageSubscriber/MessageSubscriber
  successBuildHistoryLimit: 10
  tag: harbor.tanzuworld.com/drax/subscriber-git